services:
  frontend:
    container_name: vue
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - /app/node_modules
    ports:
      - '8081:8080'
  
  node:
    container_name: node
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './server:/usr/app/'  # Mount the server directory
      - /usr/app/node_modules             # Persist node_modules
    ports:
      - "3000:3000"
