# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./ 

# Install dependencies
RUN npm install

# Copy the rest of your server files
COPY . ./  

# Expose the port your app runs on
EXPOSE 3000

# Command to run your server
CMD ["node", "server.js"] 
